/*
 * Copyright (c) 2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of Vanaheimr COSE <https://github.com/Vanaheimr/COSE.TS>
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * X.509 certificate chains [RFC 9360], against a corpus minted by Bouncy
 * Castle.
 *
 * The corpus is the point of this file. A DER parser checked against
 * certificates its own package produced would agree with itself about any
 * misreading whatsoever; these were issued by an implementation sharing no
 * code with this one, which is the only arrangement in which "it parsed" means
 * something. `tests/certificate-corpus.json` is generated by
 * `tools/CertificateCorpus` in the conformance repository, deterministically,
 * so it can be regenerated and diffed rather than trusted.
 *
 * Every check is made at a *fixed* instant. A validity period tested against
 * "now" is a test that passes until it does not, and the day it starts failing
 * has nothing to do with the code.
 */

import { describe, expect, it }              from 'vitest';

import corpus                               from './certificate-corpus.json' with { type: 'json' };

import type { CborEntry }                     from '../src/index.ts';
import { algorithmByName, cbor, CoseAlgorithms,
         CoseCertificateChain,
         CoseCertificateHash, CoseHeaders,
         CoseKey, CoseSign1, curveByName, DerReader,
         KeyUsage, label, HeaderLabel,
         X509Certificate }                   from '../src/index.ts';
import { CONTENT, hex, unhex }               from './vectors.ts';


// ------------------------------------------------------------------ corpus ---

const AT = new Date(corpus.validateAt);

const certificates = corpus.certificates as Record<string, string>;
const privateKeys  = corpus.privateKeys  as Record<string, { algorithm: string; curve?: string; keyD: string }>;

const certificate = (name: string): X509Certificate => {

    const encoded = certificates[name];

    if (encoded === undefined)
        throw new Error(`The certificate corpus holds no '${name}'!`);

    return X509Certificate.parse(unhex(encoded));

};

/** The private key of a corpus certificate, as the COSE key it signs with. */
const keyOf = (name: string): CoseKey => {

    const entry = privateKeys[name];

    if (entry === undefined)
        throw new Error(`The certificate corpus holds no private key for '${name}'!`);

    // The corpus names algorithms the way the registry does, so the registry
    // lookup is the whole of the translation.
    const algorithm = algorithmByName(entry.algorithm);

    if (algorithm === null)
        throw new Error(`Unknown algorithm '${entry.algorithm}' in the certificate corpus!`);

    if (algorithm.family === 'mldsa')
        return CoseKey.fromAkpSeed(algorithm, unhex(entry.keyD));

    const curve = curveByName(entry.curve!);

    if (curve === null)
        throw new Error(`Unknown curve '${String(entry.curve)}' in the certificate corpus!`);

    return CoseKey.fromPrivateScalar(curve, unhex(entry.keyD), { algorithm });

};

/**
 * Sign a message carrying the given chain, the way a meter would.
 *
 * The chain goes into the *protected* bucket, which is not a formality: an
 * unprotected `x5chain` can be swapped for another one without disturbing the
 * signature, and a verifier that then reports the new subject as the signer
 * has been told who signed by somebody who did not.
 */
function signWithChain(signingKey:  CoseKey,
                       chain:       readonly X509Certificate[],
                       options:     { thumbprintOf?: X509Certificate; critical?: boolean } = {}): CoseSign1 {

    const parameters: CborEntry[] = [
        [label(HeaderLabel.algorithm), cbor.int(signingKey.algorithm!.id)],
    ];

    if (options.critical === true)
        parameters.push([label(HeaderLabel.critical), cbor.array([label(HeaderLabel.x5Chain)])]);

    parameters.push([label(HeaderLabel.x5Chain), new CoseCertificateChain(chain).toCbor()]);

    if (options.thumbprintOf !== undefined)
        parameters.push([label(HeaderLabel.x5T), CoseCertificateHash.from(options.thumbprintOf).toCbor()]);

    return CoseSign1.signWithHeaders(CONTENT, signingKey, new CoseHeaders(parameters));

}


// ------------------------------------------------------------------- tests ---

describe('Reading what Bouncy Castle wrote', () => {

    it('reads every certificate of the corpus', () => {

        for (const name of Object.keys(certificates))
            expect(() => certificate(name), name).not.toThrow();

    });

    it('reads the meter certificate field by field', () => {

        const meter = certificate('meter');

        expect(meter.version).toBe(3);
        expect(meter.subject.toString()).toBe('CN=Meter 1ISA0000000042');
        expect(meter.issuer.toString()).toBe('CN=Meter Manufacturer CA');
        expect(meter.notBefore.toISOString()).toBe('2024-01-01T00:00:00.000Z');
        expect(meter.notAfter.toISOString()).toBe('2034-01-01T00:00:00.000Z');

        // The curve the whole project turns on, and the one a WebCrypto-based
        // parser could not have verified.
        expect(meter.publicKey.curve?.name).toBe('brainpoolP256r1');
        expect(meter.signatureAlgorithm.name).toBe('ES256');

        expect(meter.isCertificateAuthority).toBe(false);
        expect(meter.allows(KeyUsage.digitalSignature)).toBe(true);
        expect(meter.allows(KeyUsage.keyCertSign)).toBe(false);

    });

    it('reads a certification authority as one', () => {

        const authority = certificate('manufacturerCA');

        expect(authority.isCertificateAuthority).toBe(true);
        expect(authority.allows(KeyUsage.keyCertSign)).toBe(true);
        expect(authority.basicConstraints?.certificateAuthority).toBe(true);

    });

    it('recovers the certified key of all three families', () => {

        expect(certificate('meter').publicKey.curve?.name).toBe('brainpoolP256r1');
        expect(certificate('edwardsMeter').publicKey.curve?.name).toBe('Ed25519');

        const pq = certificate('pqMeter').publicKey;

        expect(pq.algorithm?.name).toBe('ML-DSA-65');
        expect(pq.pub?.length).toBe(1952);

    });

    it('keeps the encoding it was given, which is what a thumbprint covers', () => {

        const meter = certificate('meter');

        expect(hex(meter.encoded)).toBe(certificates.meter);
        expect(hex(meter.thumbprint())).toHaveLength(64);

    });

});


describe('Verifying a certificate against its issuer', () => {

    it('accepts a certificate its issuer really signed', () => {

        expect(certificate('meter').verifySignedBy(certificate('manufacturerCA')).verified).toBe(true);
        expect(certificate('manufacturerCA').verifySignedBy(certificate('metrologyRoot')).verified).toBe(true);

    });

    it('accepts a chain that changes curve halfway down', () => {

        // The root is on P-256 and signs a brainpoolP256r1 authority. An
        // implementation that took the curve from the certificate being
        // checked rather than from the key checking it would fail here.
        expect(certificate('manufacturerCA').publicKey.curve?.name).toBe('brainpoolP256r1');
        expect(certificate('metrologyRoot').publicKey.curve?.name).toBe('P-256');
        expect(certificate('manufacturerCA').verifySignedBy(certificate('metrologyRoot')).verified).toBe(true);

    });

    it('verifies certificates signed with EdDSA and with ML-DSA', () => {

        expect(certificate('edwardsMeter').verifySignedBy(certificate('edwardsRoot')).verified).toBe(true);
        expect(certificate('pqMeter').verifySignedBy(certificate('pqRoot')).verified).toBe(true);

    });

    it('refuses a certificate the candidate did not sign', () => {

        const wrong = certificate('meter').verifySignedBy(certificate('otherIntermediate'));

        expect(wrong.verified).toBe(false);

    });

    it('refuses a certificate whose issuer field names somebody else', () => {

        const wrong = certificate('meter').verifySignedBy(certificate('metrologyRoot'));

        expect(wrong.verified).toBe(false);
        expect(wrong.verified === false && wrong.reason).toContain('names the issuer');

    });

});


describe('Walking a chain to an anchor', () => {

    const meterChain = () => new CoseCertificateChain([certificate('meter'),
                                                       certificate('manufacturerCA')]);

    it('accepts a chain that leads to a trusted root', () => {

        expect(meterChain().validate([certificate('metrologyRoot')], { at: AT }).verified).toBe(true);

    });

    it('accepts a chain that ends at the anchor itself', () => {

        const chain = new CoseCertificateChain([certificate('meter'),
                                                certificate('manufacturerCA'),
                                                certificate('metrologyRoot')]);

        expect(chain.validate([certificate('metrologyRoot')], { at: AT }).verified).toBe(true);

    });

    it('refuses a chain to an unknown root', () => {

        const refused = meterChain().validate([certificate('otherRoot')], { at: AT });

        expect(refused.verified).toBe(false);
        expect(refused.verified === false && refused.reason).toContain('neither a trust anchor nor issued by one');

    });

    it('refuses a chain without any anchor at all', () => {

        const refused = meterChain().validate([], { at: AT });

        expect(refused.verified).toBe(false);
        expect(refused.verified === false && refused.reason).toContain('at least one trust anchor');

    });

    it('refuses an expired certificate', () => {

        const chain   = new CoseCertificateChain([certificate('expiredMeter'),
                                                  certificate('manufacturerCA')]);
        const refused = chain.validate([certificate('metrologyRoot')], { at: AT });

        expect(refused.verified).toBe(false);
        expect(refused.verified === false && refused.reason).toContain('expired');

    });

    it('refuses a certificate that is not valid yet', () => {

        const chain   = new CoseCertificateChain([certificate('notYetValidMeter'),
                                                  certificate('manufacturerCA')]);
        const refused = chain.validate([certificate('metrologyRoot')], { at: AT });

        expect(refused.verified).toBe(false);
        expect(refused.verified === false && refused.reason).toContain('not valid before');

    });

    it('accepts the expired certificate at a time when it was not expired', () => {

        const chain = new CoseCertificateChain([certificate('expiredMeter'),
                                                certificate('manufacturerCA')]);

        expect(chain.validate([certificate('metrologyRoot')],
                              { at: new Date('2020-09-01T00:00:00Z') }).verified).toBe(true);

    });

    it('refuses an issuer that is not a certification authority', () => {

        const chain   = new CoseCertificateChain([certificate('meterUnderNonCA'),
                                                  certificate('notACA')]);
        const refused = chain.validate([certificate('metrologyRoot')], { at: AT });

        expect(refused.verified).toBe(false);
        expect(refused.verified === false && refused.reason).toContain('not a certification authority');

    });

    it('refuses an end-entity certificate that may not sign', () => {

        const chain   = new CoseCertificateChain([certificate('encipherOnlyMeter'),
                                                  certificate('manufacturerCA')]);
        const refused = chain.validate([certificate('metrologyRoot')], { at: AT });

        expect(refused.verified).toBe(false);
        expect(refused.verified === false && refused.reason).toContain('not allowed to create digital signatures');

    });

    it('refuses a chain whose links do not hold', () => {

        const chain   = new CoseCertificateChain([certificate('meter'),
                                                  certificate('otherIntermediate')]);
        const refused = chain.validate([certificate('otherRoot')], { at: AT });

        expect(refused.verified).toBe(false);

    });

    it('walks a chain signed with EdDSA and one signed with ML-DSA', () => {

        expect(new CoseCertificateChain([certificate('edwardsMeter')])
                   .validate([certificate('edwardsRoot')], { at: AT }).verified).toBe(true);

        expect(new CoseCertificateChain([certificate('pqMeter')])
                   .validate([certificate('pqRoot')], { at: AT }).verified).toBe(true);

    });

});


describe('The CBOR form of a chain [RFC 9360]', () => {

    it('writes a single certificate as a bare byte string', () => {

        const encoded = new CoseCertificateChain([certificate('meter')]).toCbor();

        expect(encoded.type).toBe('bytes');

    });

    it('writes two or more as an array', () => {

        const encoded = new CoseCertificateChain([certificate('meter'),
                                                  certificate('manufacturerCA')]).toCbor();

        expect(encoded.type).toBe('array');

    });

    it('reads back what it wrote, both shapes', () => {

        for (const chain of [[certificate('meter')],
                             [certificate('meter'), certificate('manufacturerCA')]]) {

            const written = new CoseCertificateChain(chain).toCbor();
            const read    = CoseCertificateChain.fromCbor(written);

            expect(read.certificates.map(each => hex(each.encoded)))
                .toStrictEqual(chain.map(each => hex(each.encoded)));

        }

    });

    it('refuses an array of one, which RFC 9360 spells as 2*certs', () => {

        expect(() => CoseCertificateChain.fromCbor(
            cbor.array([cbor.bytes(certificate('meter').encoded)])
        )).toThrow(/bare byte string/u);

    });

    it('refuses a chain of something other than byte strings', () => {

        expect(() => CoseCertificateChain.fromCbor(cbor.int(1))).toThrow();
        expect(() => CoseCertificateChain.fromCbor(
            cbor.array([cbor.bytes(certificate('meter').encoded), cbor.int(1)])
        )).toThrow(/must be a byte string/u);

    });

});


describe('The thumbprint names a certificate, it does not vouch for one', () => {

    it('matches the certificate it was taken from', () => {

        const meter = certificate('meter');

        expect(CoseCertificateHash.from(meter).matches(meter).verified).toBe(true);

    });

    it('does not match another one', () => {

        const refused = CoseCertificateHash.from(certificate('manufacturerCA'))
                            .matches(certificate('meter'));

        expect(refused.verified).toBe(false);

    });

    it('survives its CBOR form', () => {

        const thumbprint = CoseCertificateHash.from(certificate('meter'), CoseAlgorithms.SHA384);
        const read       = CoseCertificateHash.fromCbor(thumbprint.toCbor());

        expect(read.algorithm.name).toBe('SHA-384');
        expect(hex(read.value)).toBe(hex(thumbprint.value));
        expect(read.matches(certificate('meter')).verified).toBe(true);

    });

    it('refuses a hash algorithm it can not compute', () => {

        // SHA-1 is registered and is deliberately not implemented on either
        // side, so a thumbprint naming it is refused rather than guessed at.
        expect(() => CoseCertificateHash.fromCbor(
            cbor.array([cbor.int(-14), cbor.bytes(new Uint8Array(20))])
        )).toThrow(/not a hash algorithm/u);

    });

    it('takes a signature algorithm to mean its own digest, as Styx does', () => {

        // Strictly, -7 names ECDSA and not a hash. Both implementations read
        // it as the digest that algorithm uses, which is the lenient reading —
        // and being lenient in the same way is what matters here, since the
        // two have to reach the same verdict about the same message.
        const thumbprint = CoseCertificateHash.fromCbor(
                               cbor.array([cbor.int(-7), cbor.bytes(certificate('meter').thumbprint())]));

        expect(thumbprint.algorithm.hash).toBe('sha256');
        expect(thumbprint.matches(certificate('meter')).verified).toBe(true);

    });

});


describe('DER is read strictly, because that is where differentials live', () => {

    it('refuses an indefinite length', () => {

        expect(() => new DerReader(unhex('3080'), 'test').read()).toThrow(/indefinite/u);

    });

    it('refuses a length that could have been shorter', () => {

        // 0x81 0x01 says "one octet of length, whose value is 1" — which the
        // short form expresses in one octet.
        expect(() => new DerReader(unhex('30810100'), 'test').read()).toThrow(/short form/u);

    });

    it('refuses a leading zero in a long-form length', () => {

        expect(() => new DerReader(unhex('30820080'), 'test').read()).toThrow(/leading zero/u);

    });

    it('refuses a record that claims more than it has', () => {

        expect(() => new DerReader(unhex('3005AABB'), 'test').read()).toThrow(/remain/u);

    });

    it('refuses trailing data after a certificate', () => {

        expect(() => X509Certificate.parse(unhex(`${certificates.meter!}00`)))
            .toThrow(/octets follow/u);

    });

    it('refuses a truncated certificate', () => {

        const meter = certificates.meter!;

        expect(() => X509Certificate.parse(unhex(meter.slice(0, meter.length - 20)))).toThrow();

    });

});


describe('A chain becomes an answer only with the key that signed', () => {

    const anchors = () => [certificate('metrologyRoot')];

    const chain   = () => [certificate('meter'), certificate('manufacturerCA')];

    it('names the signer when everything holds', () => {

        const signed = signWithChain(keyOf('meter'), chain());
        const parsed = CoseSign1.parse(signed.toBytes());

        const result = parsed.verifyWithCertificateChain(anchors(), { at: AT });

        expect(result.verified).toBe(true);
        expect(result.verified === true && result.signer.subject.toString())
            .toBe('CN=Meter 1ISA0000000042');

    });

    it('refuses a chain certifying another key than the one that signed', () => {

        // The chain is impeccable and leads to the trusted root. It simply
        // certifies somebody else, which is the failure a chain check alone
        // never catches.
        const signed = signWithChain(keyOf('meter'),
                                     [certificate('strangerMeter'), certificate('manufacturerCA')]);

        const result = CoseSign1.parse(signed.toBytes())
                           .verifyWithCertificateChain(anchors(), { at: AT });

        expect(result.verified).toBe(false);

        // ...and the chain on its own does validate, which is the point.
        expect(new CoseCertificateChain([certificate('strangerMeter'), certificate('manufacturerCA')])
                   .validate(anchors(), { at: AT }).verified).toBe(true);

    });

    it('refuses a message carrying no chain at all', () => {

        const signed = CoseSign1.sign(CONTENT, keyOf('meter'));
        const result = CoseSign1.parse(signed.toBytes())
                           .verifyWithCertificateChain(anchors(), { at: AT });

        expect(result.verified).toBe(false);
        expect(result.verified === false && result.reason).toContain('carries no certificate chain');

    });

    it('refuses a thumbprint naming a certificate other than the one that travelled', () => {

        const signed = signWithChain(keyOf('meter'), chain(),
                                     { thumbprintOf: certificate('manufacturerCA') });

        const result = CoseSign1.parse(signed.toBytes())
                           .verifyWithCertificateChain(anchors(), { at: AT });

        expect(result.verified).toBe(false);
        expect(result.verified === false && result.reason).toContain('does not name the certificate');

    });

    it('accepts a thumbprint that names the end-entity certificate', () => {

        const signed = signWithChain(keyOf('meter'), chain(),
                                     { thumbprintOf: certificate('meter') });

        expect(CoseSign1.parse(signed.toBytes())
                   .verifyWithCertificateChain(anchors(), { at: AT }).verified).toBe(true);

    });

    it('works the same for an Edwards and for a post-quantum signer', () => {

        for (const [signer, anchor] of [['edwardsMeter', 'edwardsRoot'],
                                        ['pqMeter',      'pqRoot']] as const) {

            const signed = signWithChain(keyOf(signer), [certificate(signer)]);
            const result = CoseSign1.parse(signed.toBytes())
                               .verifyWithCertificateChain([certificate(anchor)], { at: AT });

            expect(result.verified, signer).toBe(true);

        }

    });

    it('refuses a tampered payload even with a perfect chain', () => {

        const signed  = signWithChain(keyOf('meter'), chain());
        const message = CoseSign1.parse(signed.toBytes());

        const tampered = new CoseSign1(message.protectedHeaderBytes,
                                       message.unprotectedHeader,
                                       new TextEncoder().encode('This is the contenu.'),
                                       message.signature,
                                       message.isTagged);

        expect(tampered.verifyWithCertificateChain(anchors(), { at: AT }).verified).toBe(false);

    });

});


describe('A sender may demand that the chain be processed', () => {

    it('is refused by a plain verification, and accepted by a chain one', () => {

        const signed = signWithChain(keyOf('meter'),
                                     [certificate('meter'), certificate('manufacturerCA')],
                                     { critical: true });

        const message = CoseSign1.parse(signed.toBytes());

        // Whoever verifies with a bare public key has not looked at any
        // certificate, and must not claim to have understood the demand.
        const bare = message.verify(keyOf('meter').publicKey());

        expect(bare.verified).toBe(false);
        expect(bare.verified === false && bare.reason).toContain('x5chain');

        expect(message.verifyWithCertificateChain([certificate('metrologyRoot')], { at: AT }).verified)
            .toBe(true);

    });

});
